spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/depp
    username: francis
    password: password

  jpa:
    properties:
      hibernate:
        format_sql: true

        jdbc:
          time_zone: UTC+1

    hibernate:
      ddl-auto: update
    show-sql: false

#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=password
##spring.datasource.schema=classpath:sql/schema.sql
##spring.datasource.initialization-mode=always
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#server.port=8081
server:
  port: 8090
